<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<!--
	Name: Elisabeth Feeley
	Date: Winter 2013
	Description: Home Page
	Assistance: N/A
-->	 

	<head>
	   <title>Elisabeth Feeley</title>
	   <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
		
		<link href="design.css" rel="stylesheet" type="text/css" />
		
		<script type="text/javascript" src="clock.js"> </script>
	</head>

	<body onload="updateClock(); setInterval('updateClock()', 1000 )">
		
		<div id="header">
			<p>
				Elisabeth Feeley
			</p>
			<p>
				Winter 2013 &bull; Web Programming &bull; CSC322
			</p>
		</div>
		
		<div id="menu">
		   <a href="index.php">Home</a>
		   <a href="assignments.php">Assignments</a>
		   <a href="portfolio.php">Portfolio</a>
		   <a href="links.php">Links</a>
		</div>
		